config/routes.rb
EPICS::Application.routes.draw do

  get "contact/index"

  get "contact/new"

  post "contact/create"

  get "contact/edit"

  post "contact/update"
  
  get "contact/send_email"

  get "contact/void"

  get "person/add_person"
  post "person/new_person"
  get "person/get_name"

  get "epics_exchange/index"
  post "epics_exchange/create"
  get "epics_exchange/new"
  get "epics_exchange/give_item"
  post "epics_exchange/give_item"
  get "epics_exchange/receive_item"
  post "epics_exchange/receive_item"
  post "epics_exchange/exchange"
  get "epics_exchange/exchange"
  get "epics_exchange/summary"
  post "epics_exchange/remove_product_from_issue_cart"
  post "epics_exchange/remove_product_from_receive_cart"
  get "epics_exchange/print_exchanged_items_label"
  get "epics_exchange/print_exchanged_items_from_view"
  get "epics_exchange/exchange_items_label"
  get "epics_exchange/exchange_items_data"

  match '/login' => "user#login"
  match '/logout' => "user#logout"
  post "user/authenticate"
  get "user/enter_workstation"
  post "user/locations"
  get "/user/new"
  post "user/create"
  get "user/summary"
  get "user/edit"
  get "user/change_password"
  post "user/change_password"
  get "user/change_username"
  post "user/change_username"
  get "user/change_user_role"
  post "user/change_user_role"
  get "user/void"

  get "home/dispensary"

  get "orders/index"
  post "orders/create"
  get "orders/new"
  get "orders/edit"
  get "orders/update"
  get "orders/void"
  post "orders/select"
  get "orders/select"
  post "orders/dispense"
  get "orders/lend"
  get "orders/get_authoriser"
  get "orders/lend_create"
  post "orders/lend_create"
  get "orders/lend_index"
  post "orders/lend_index"
  post "orders/remove_product_from_cart"
  get "orders/return_loans"
  post "orders/remove_product_from_lend_cart"
  post "orders/reimburse_index"
  get "orders/reimburse_index"
  get "orders/select_item_to_return"
  post "orders/select_item_to_return"
  post "/orders/remove_reimburse_from_cart"
  get "orders/donate"
  get "orders/donate_index"
  post "orders/donate_index"
  get "orders/select_donation_item"
  post "orders/select_donation_item"
  post "orders/remove_product_from_donate_cart"

  get "stock_details/index"
  get "stock_details/new"
  post "stock_details/create"
  get "stock_details/checkout"
  get "stock_details/summary"
  get "stock_details/edit"
  post "stock_details/update"
  get "stock_details/void"
  post "stock_details/void"
  post "stock_details/board_off_stock"
  get "stock_details/borrow"
  post "stock_details/borrow"
  post "stock_details/remove_product_from_cart"
  get "stock_details/return_index"
  post "stock_details/return_index"
  post "stock_details/return_index"
  get "stock_details/return_index"
  get "stock_details/return_item"
  get "stock_details/board_off"
  get "stock_details/edit_stock_details"
  post "stock_details/save_edited_stock_details"
  get "stock_details/print_received_items_label"
  get "stock_details/receive_items_data"
  get "stock_details/receive_items_label"
  post "stock_details/receive_items_label"
  get "stock_details/print_received_items_from_view"
  get "stock_details/print_borrowed_items_label"
  get "stock_details/print_borrowed_items_label"
  get "stock_details/borrow_items_label"
  get "stock_details/borrow_items_data"
  get "stock_details/print_borrowed_items_from_view"
  get "stock_details/print_received_back_items_label"
  get "stock_details/print_received_back_items_from_view"
  get "stock_details/receive_back_items_label"
  get "stock_details/receive_back_items_data"
  get "stock_details/edit_current_quantity"
  post "stock_details/edit_current_quantity"
  get "stock_details/void_transaction"

  get "stock/index"
  get "stock/new"
  get "stock/get_witness_names"
  post "stock/create"
  get "stock/edit"
  post "stock/update"
  get "stock/void"
  get "stock/borrow"
  get "stock/borrow_index"
  post "stock/borrow_index"
  get "stock/receive_loan_returns"
  post "stock/remove_product_from_borrow_cart"
  get "stock/get_batches_not_reimbursed_to_facility"
  post "stock/get_returners_details"
  get "stock/reimburse_index"
  get "/stock/get_lent_items"
  get "stock/get_returners_details"
  get "stock/get_items_by_batch_number"
  get "/stock/confirmations"
  post "/stock/authorize_transaction"
  get "stock/get_details_for_pending_trans"
  get 'stock/get_items_by_order_id'

  get "location_type/index"
  get "location_type/new"
  post "location_type/create"
  get "location_type/edit"
  post "location_type/update"
  get "location_type/void"

  get "location/index"
  get "location/new"
  post "location/create"
  get "location/edit"
  post "location/update"
  get "location/void"
  get "location/search"
  get "location/print_location_menu"
  post "location/print_location"
  get "location/location_label"

  get "product_category/index"

  get "product_category/new"

  post "product_category/create"

  get "product_category/edit"

  post "product_category/update"

  get "product_category/void"

  get "order_type/index"

  get "order_type/new"

  post "order_type/create"

  get "order_type/edit"

  post "order_type/update"

  get "order_type/void"

  get "supplier/index"

  get "supplier/new"

  post "supplier/create"

  get "supplier/edit"

  post "supplier/update"

  get "supplier/void"

  get "product/index"
  get "product/new"
  post "product/create"
  get "product/edit"
  post "product/update"
  get "product/void"
  post "product/void"
  get "product/get_products"
  get "product/get_products_by_location"
  match 'get_batch' => 'product#get_batch_details'
  get "product/find_by_name_or_code"
  get "product/search"
  get "product/view"
  post "product/view"
  get "product/edit_product"
  post "product/edit_product"
  post "product/save_edited_product"
  get "product/stock_card"
  post "product/stock_card"
  match 'edit_cost/:id' => 'product#edit_cost', :as => :edit_cost
  post "product/edit_cost"
  post "product/print_stock_card"
  get "product/stock_card_printable"
  get "product/select_drug"
  post "product/select_drug"
  get "product/product_batches"
  post "product/product_batches"
  get "product/modify_expiry_date"
  post "product/modify_expiry_date"
  get "product/select_drug_menu"
  match 'edit_item/:id' => 'product#edit_index', :as => :edit_item
  get "product/edit_index"

  get "product/expire"

  get "product_type/index"

  get "product_type/new"

  post "product_type/create"

  get "product_type/edit"

  post "product_type/update"

  get "product_type/void"

  get "product_units/index"

  get "product_units/new"

  get "product_units/edit"

  post "product_units/create"

  post "product_units/update"

  get "product_units/void"

  get "supplier_type/new"

  post "supplier_type/create"

  get "supplier_type/index"

  get "supplier_type/edit"

  get "supplier_type/void"

  post "supplier_type/update"

  get "report/drug_availability"
  get "report/drug_availability_printable"
  post "report/drug_availability_printable"
  post "report/daily_dispensation"
  post "report/daily_dispensation_printable"
  get "report/store_room"
  post "report/store_room_printable"
  get "report/view_alerts"
  get "report/select_store"
  match 'alerts/:name' => 'report#alerts', :as => :alerts
  get "report/select_date_range"
  post "report/monthly_report"
  post "report/print_monthly_report"
  get "report/monthly_report_printable"
  post "report/monthly_report_printable"
  get "report/select_daily_dispensation_date"
  match 'drug_daily_dispensation/:id/:date' => 'report#drug_daily_dispensation', :as => :drug_daily_dispensation
  get "report/expired_items"
  get "report/select_date_ranges"
  post "report/disposed_items"
  post "report/print_drug_availability_report"
  post "report/print_store_room_report"
  get "report/store_room_printable"
  post "report/print_daily_dispensation_report"
  get "report/daily_dispensation_printable"
  get 'report/missing_items'
  post 'report/print_disposed_items_report'
  get 'report/disposed_items_printable'
  post "report/audit"
  post "report/received_items"
  post "report/print_expired_items_report"
  get "report/expired_items_printable"
  get "report/items_to_expire_next_six_months_attachment"
  post "report/items_to_expire_next_six_months_attachment"
  get "report/items_to_expire_next_six_months_to_pdf"
  post "report/items_to_expire_next_six_months_to_pdf"
  get "report/daily_dispensation_attachment"
  post "report/daily_dispensation_attachment"
  get "report/daily_dispensation_to_pdf"
  post "report/daily_dispensation_to_pdf"
  get "report/received_items_attachment"
  post "report/received_items_attachment"
  get "report/received_items_to_pdf"
  post "report/received_items_to_pdf"
  get "report/monthly_report_attachment"
  get "report/monthly_report_to_pdf"

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    (session || {}).each do |name , values|
      next if name == 'location_name'
      next if name == 'location_id'
      next if name == 'user_id'
      next if name == 'flash'
      next if name == '_csrf_token'
      session[name] = nil
    end 

    @application = [
      ["Issue Items","orders/new","dispense.png"],
      ["Receive Items","stock/new","receive.png"],
      ["Exchange Items","epics_exchange/index","exchange_drugs1.png"],
      ["Lend Items","orders/lend","lend_item.png"],
      ["Borrow Items","stock/borrow","borrow_drugs.png"],
      ["Donate Items","/orders/donate","donate_item.png"],
      ["Receive Items Back","/stock/receive_loan_returns","receive_back.png"],
      ["Reimburse Borrowed Items","orders/return_loans","reimburse_items.jpg"],
      ["Search",'/product/search',"search.png"]
    ]

    @reports = [
      ["Drug Availability","/report/select_store?report=drug_availability","available_drugs.png"],
      ["Daily Dispensation","/report/select_daily_dispensation_date","daily_dispense.png"],
      ["Central Hospital Monthly LMIS Report","/report/select_date_range","monthly_report.png"],
      ["Audit Report","/report/select_date_ranges?name=audit","audit_report.png"],
      ["View Received/Issued","/report/select_date_ranges?name=received_items","view_issued_received.png"],
      ["View Store Room","/report/select_store","first_aid_kit_icon.png"],
      ["View expired items","report/expired_items","expired.jpeg"],
      ["View Disposed items","/report/select_date_ranges","disposal.png"],
      ["View alerts","/report/view_alerts","alert_list.png"]
    ]

    @activities = [
        ["Change Password", "user/change_password", "change_password.png"],
        ["Edit Username", "user/change_username", "change_username.png"]
    ]

    @administration = [
      ["Add Items","/product/new","add_items.png"],
      ["Print Location","/location/print_location_menu","emblem_print.png"],
      ["Set Contacts","/contact/index","contacts.png"],
      ["Edit Expiry Date","/product/select_drug_menu","edit_expiry_date.png"]
    ]

    if User.current.epics_user_role.name == "Administrator"
      @administration << ["Set Item Units","/product_units/index","units_icon.png"] << ["Set Item Types","/product_type/index","set_items.png"]
      @administration << ["Set Item Categories","/product_category/index","Item_categories.png"]# << ["Set Order Types","/order_type/index","order_type.png"]
      @administration << ["Set Supplier Types","/supplier_type/index","supplier_type.png"] << ["Set Suppliers","/supplier/index","suppliers.png"]
      @administration << ["Set Locations","/location/index","sysuser.png"] << ["Set Location Types","/location_type/index","workstations.png"]
      @administration << ["Add User","/user/new","add_user.png"]
      @administration << ["Edit User","/user/edit","user_edit2.png"]

      #<< ["Add person","person/add_person","add_user.png"]

    end

    @buttons_count = @application.length
    @buttons_count = @reports.length if @reports.length > @buttons_count
    @buttons_count = @activities.length if @activities.length > @buttons_count
    @buttons_count = @administration.length if @administration.length > @buttons_count

    @reminders = EpicsLendBorrowAuthorizer.find(:all, :conditions => ["voided = ? AND authorized = ?",false,false]).length rescue 0

    ############################ alerts ######################################
    if params[:show_alerts_popup] == 'true'
      @alerts = EpicsReport.alerts
    else
      @alerts = []
    end
    ################################ end #####################################

    render :layout => false
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_alerts.html.erb
<style>
.alerts {
  width:95%;
}

.alerts th {
  text-align: left;
  padding: 10px;
  font-size: 30px;
  border-style: outset;
  line-height: 70px;
  border-width: 0px 0px 1px 0px;
}

.alerts td {
  text-align: right;
  padding: 10px;
  font-size: 30px;
  line-height: 70px;
  border-style: outset;
  border-width: 0px 0px 1px 0px;
}

.btn {
  -moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
  -webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
  box-shadow:inset 0px 1px 0px 0px #bbdaf7;
  background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5) );
  background:-moz-linear-gradient( center top, #79bbff 5%, #378de5 100% );
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
  background-color:#79bbff;
  -moz-border-radius:42px;
  -webkit-border-radius:42px;
  border-radius:42px;
  border:1px solid #84bbf3;
  display:inline-block;
  color:#ffffff;
  font-family:arial;
  font-size:17px;
  font-weight:bold;
  padding:6px 24px;
  text-decoration:none;
  text-shadow:1px 1px 0px #528ecc;
  width: 50%;
  text-align: center;
}.btn:hover {
  background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #378de5), color-stop(1, #79bbff) );
  background:-moz-linear-gradient( center top, #378de5 5%, #79bbff 100% );
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#378de5', endColorstr='#79bbff');
  background-color:#378de5;
}.btn:active {
  position:relative;
  top:1px;
}

.close {
  width: 300px;
  height: 70px;
}
</style>

<table class="alerts">
  <%(@alerts || {}).each do |name , count|%>
  <tr>
    <th><%=name%></th>
    <%if count > 0 %>
      <td><%= link_to count, alerts_url(:name => name),:class => 'btn' %></td>
    <%else%>
      <td><a href="#" class='btn'><%=count%></a></td>
    <%end%>
  </tr>
  <%end%>
   <tr>
    <td colspan="2" style="text-align: center;">
      <input type="button" onclick="hideLayer();" value="View later" class="btn close" />
    </td>
   </tr>
</table>

app/views/home/dispensary.html.erb
Drug dispensation for patients

app/views/home/index.html.erb
<html>
<head>
  <title>Home</title>
  <style type="text/css">
      body {
          background-color: #fff;
          margin: 20px;
          font-family: "Nimbus Sans L", "Arial Narrow", sans-serif;
          overflow: hidden;
          color: #000;
          -moz-user-select: none;
      }

      .buttons-table td {
          text-align: center;
      }

      .buttons-table img {
          width: 128px;
          height: 128px;
      }

      #shadow, #question {
          -moz-user-select: none;
      }

      div {
          -moz-user-select: none;
      }
  </style>

  <%= stylesheet_link_tag "disable_page" %>
  <%= javascript_include_tag "disable_page"%>
  <%= javascript_include_tag "cookies"%>

  <script type="text/javascript">
      setTimeout("setCookie();",300)
      <!--

      function __$(id){
          return document.getElementById(id);
      }

      function switchTab(tab){
          var tabs = ["application", "reports", "my_activities", "administration"];

          for(var i = 0; i < tabs.length; i++){
              __$(tabs[i]).style.borderBottom = "1px solid #5496ef";
              __$(tabs[i]).style.paddingTop = "60px";
          }

          __$(tab).style.borderBottom = "5px solid #5496ef";
          __$(tab).style.paddingTop = "65px";

          switch(tab.toLowerCase()){
              case "application":
                  loadApplicationMenu();
                  break;
              case "reports":
                  loadReportsMenu();
                  break;
              case "my_activities":
                  loadActivitiesMenu();
                  break;
              case "administration":
                  loadAdministrationMenu();
                  break;
          }
      }

      function adjustView(){
      }

      function loadAdministrationMenu(){
          resetButtonsTable();
      <%
  count = 0
  (@administration || []).each do |name,path,image|%>
          b = document.getElementById('button'+(<%=count+=1%>));
          b.innerHTML = '<div style="width: 200px; text-align: center; padding: 10px;">';
          b.innerHTML += "<a href='<%=path%>'><img src='images/<%=image%>' /></a>";
          b.innerHTML += '<div>' + "<%=name%>" + '</div></a></div>'
      <%end%>
      }

      function loadApplicationMenu(){
          resetButtonsTable();
      <%
  count = 0
  (@application || []).each do |name,path,image|%>
          b = document.getElementById('button'+(<%=count+=1%>));
          b.innerHTML = '<div style="width: 200px; text-align: center; padding: 10px;">';
          b.innerHTML += '<a href="<%=path%>"><img src="images/<%=image%>" /></a>';
          b.innerHTML += '<div>' + "<%=name%>" + '</div></a></div>'
      <%end%>
      }

      function loadReportsMenu(){
          resetButtonsTable();
      <%
  count = 0
  (@reports || []).each do |name,path,image|%>
          b = document.getElementById('button'+(<%=count+=1%>));
          b.innerHTML = '<div style="width: 200px; text-align: center; padding: 10px;">';
          b.innerHTML += '<a href="<%=path%>"><img src="images/<%=image%>" /></a>';
          b.innerHTML += '<div>' + "<%=name%>" + '</div></a></div>'
      <%end%>
      }

      function loadActivitiesMenu(){
          resetButtonsTable();
      <%
  count = 0
  (@activities || []).each do |name,path,image|%>
          b = document.getElementById('button'+(<%=count+=1%>));
          b.innerHTML = '<div style="width: 200px; text-align: center; padding: 10px;">';
          b.innerHTML += '<a href="<%=path%>"><img src="images/<%=image%>" /></a>';
          b.innerHTML += '<div>' + "<%=name%>" + '</div></a></div>'
      <%end%>
      }

      function resetButtonsTable() {
          var t = document.getElementsByClassName('buttons-table')[0];
          var tds = t.getElementsByTagName("td");
          for(var i=0;i<tds.length;i++) {
              tds[i].innerHTML = null;
          }
      }

      //-->

      function switchToActiveTab(){
          active_tab = readCookie('active-tab');
          if (active_tab){
              switchTab(active_tab)
          }
          else{
              loadApplicationMenu();
          }

      }
  </script>
</head>

<body onresize="adjustView()" onload="adjustView(); switchToActiveTab();">
<table id="parent_table" width="100%" cellspacing="0" cellpadding="10">
  <tr id="main-menu">
    <td id="application" style="border-bottom: 5px solid #5496ef; font-size: 18px;
            padding-top: 65px; width: 100px; cursor: pointer;" align="center"
        onclick="switchTab(this.id)">
      Application
    </td>
    <td id="reports" style="border-bottom: 1px solid #5496ef; font-size: 18px;
            padding-top: 60px; width: 80px; cursor: pointer;" align="center"
        onclick="switchTab(this.id)">
      Reports
    </td>
    <td id="my_activities" style="border-bottom: 1px solid #5496ef; font-size: 18px;
            padding-top: 60px; width: 110px; cursor: pointer;" align="center"
        onclick="switchTab(this.id)">
      My Activities
    </td>
    <td id="administration" style="border-bottom: 1px solid #5496ef; font-size: 18px;
            padding-top: 60px; width: 130px; cursor: pointer;" align="center"
        onclick="switchTab(this.id)">
      Administration
    </td>
    <td style="border-bottom: 1px solid #5496ef;">
      &nbsp;
    </td>
    <td style="width: 100px; border-bottom: 1px solid #5496ef;">
      <img src="/images/<%= (File.exists?("#{Rails.root}/public/images/app.png") ?
              "app.png" : "baobab.png") %>" height="80" style="float: right;" />
    </td>
  </tr>
  <tr>
    <td colspan="6" style="padding: 0px;">
      <div id="container" style="width: 100%; height: 540px; overflow: auto;">

        <table style="width:100%" class="buttons-table">
          <%
             count = 0
             1.upto(@buttons_count).each do |number|%>
              <tr>
                <td id='button<%=count+=1%>'></td>
                <td id='button<%=count+=1%>'></td>
                <td id='button<%=count+=1%>'></td>
              </tr>
          <%end%>
        </table>

      </div>
    </td>
  </tr>
  <tr>
    <td colspan="6" style="border-top: 1px solid #5496ef;">
      &nbsp;
    </td>
  </tr>
</table>

<div id="nav" style="width: 100%; height: 90px;
        left: 0px; position: absolute; bottom: 0px;">
  <table style="width: 100%" >
    <tr>
      <td style="font-size: 25px;font-weight: bold;color: #708090;padding-left: 20px;">
        User : <%= User.current.username %>
      </td>
      <td style="font-size: 25px;font-weight: bold;color: #708090;">
        Location : <%= session[:location_name] %>
      </td>
      <% if @reminders > 0 %>
          <td onclick="window.location= '/stock/confirmations'" style="font-size: 25px;width: 75px; vertical-align: top;
                  background-image:url('/images/alert.png');background-repeat:no-repeat;background-position: center bottom ">
            <div style="border: 0.1em solid #000000;width: 35px; border-radius: 20px;text-align:center; color: #ffffff;background-color: #ff0000;">
              <%= @reminders %>
            </div>
          </td>
      <%end%>
      <td>
        <img src="/images/Log-Out-icon.png" height="65" style="margin-right: 20px;
                margin-top: 0px; cursor: pointer; float: right;" onclick="window.location='/logout'" />
      </td>

    </tr>
  </table>
</div>


<div id="shadow" class="opaqueLayer"> </div>
<div id="question" class="questionLayer" style="font-size: 0.9em;">
  <%= render "alerts" %>
</div>
</div>

<% unless @alerts.blank? %>
    <script>
        showLayer('question');
    </script>
<%end%>
</body>
</html>